# Generated by Django 6.0.6 on 2026-06-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_category_options_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
