# Generated by Django 6.0.6 on 2026-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Preparing"),
                    ("r", "Ready"),
                    ("s", "Served"),
                    ("b", "Billed"),
                ],
                default="p",
                max_length=2,
            ),
        ),
    ]
