# Generated by Django 6.0.6 on 2026-06-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_kitchen_station_menuitem_default_priority_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KITCHEN_STATION",
            new_name="KitchenStation",
        ),
    ]
