# Generated by Django 6.0.6 on 2026-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_rename_kitchen_station_kitchenstation"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenstation",
            name="code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
