# Generated by Django 6.0.6 on 2026-06-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_kitchenstation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="orders.kitchenstation",
            ),
        ),
    ]
